# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
#
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

def fib_o_what
  sol_val = 0
  x, y = 1, 2
  while y < 4000000
  sol_val += y if y.even?
    x, y = y, (x+y)
  end
  sol_val
end

puts fib_o_what #  expecting 4613732
