// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.


var fib_o_what = function () {
  sol = 0;
  x = 1;
  y = 2;
  while (y < 4000000) {
    if (y % 2 === 0) {
      sol += y;
    }
    z = x+y;
    x = y;
    y = z;
  }
console.log(sol);
};

fib_o_what() //  expecting 4613732
