// Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
// By starting with 1 and 2, the first 10 terms will be:

// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

// By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
// find the sum of the even-valued terms.

public class Problem02 {
    public static void main(String[] args) {
        int[] fibo = new  int[]{1,1};
        int newFib;
        int sum = 0;

        while(sum < 4000000) {
            newFib = fibo[0] + fibo[1];
            if (newFib % 2 == 0) {
                sum += newFib;
            }
            fibo[0] = fibo[1];
            fibo[1] = newFib;
        }
        System.out.println(sum);
    }
}